# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require "motion/project"
require File.expand_path(File.dirname(__FILE__) + "/../lib/quickie_motion")

Motion::Project::App.setup do |app|
  app.name = "quickie_motion_test"
end
